services:
  - type: web
    name: memoryos
    env: node
    buildCommand: |
      npm install
      npm run build
      ls -la dist
      ls -la dist/client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: "10000"
    healthCheckPath: /api/health
    healthCheckTimeout: 300
    buildFilter:
      paths:
        - client/**
        - server/**
        - shared/**
        - package.json
        - tsconfig*.json
        - vite.config.ts
    startCheckTimeout: 120
