services:
  - type: web
    name: memoryos
    env: node
    buildCommand: |
      npm install
      npm run build
      npm run postbuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
    healthCheckPath: /api/health
    buildFilter:
      paths:
        - client/**
        - server/**
        - shared/**
        - package.json
        - tsconfig*.json
        - vite.config.ts
    startCheckTimeout: 120
